# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931589cbada2aafeb73186d40f2b7dc6cd6f91923aacd4444719b4265ba4232885b460bec51eb6adb3efd42193e749854501fe1757c9b91adf42e7a5e37e174c

test:
  secret_key_base: 9671e133147e56b904a431ee9f776cf8a2c647f51e97e3ef7ab5d731fa705f863592f3ad83aabc4e427af8774a72a83abdb81e71646abfd0b89cd31494cf4e24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
